

FUNCTION TEST_math()
    Print("math.agc")
    Print("")
    Print("=======================================================================")
    Print1("        PiQ = ", PiQ        , 4, -1)
    Print1("        PiH = ", PiH        , 4, -1)
    Print1("         Pi = ", Pi         , 4, -1)
    Print1("        Pi2 = ", Pi2        , 4, -1)
    Print1("        Pi3 = ", Pi3        , 4, -1)
    Print1("        Pi4 = ", Pi4        , 4, -1)
    Print("")
    Print1("      PiRcp = ", PiRcp      , 4, -1)
    Print1("     Pi2Rcp = ", Pi2Rcp     , 4, -1)
    Print1("     Pi3Rcp = ", Pi3Rcp     , 4, -1)
    Print1("     Pi4Rcp = ", Pi4Rcp     , 4, -1)
    Print("")
    Print("=======================================================================")
    Print1("      Sqrt2 = ", Sqrt2      , 4, -1)
    Print1("   Sqrt2Rcp = ", Sqrt2Rcp   , 4, -1)
    Print("")
    Print1("      Sqrt3 = ", Sqrt3      , 4, -1)
    Print1("   Sqrt3Rcp = ", Sqrt3Rcp   , 4, -1)
    Print("")
    Print("=======================================================================")
    //Print1("TwoSubSqrt2 = ", TwoSubSqrt2, 4, -1)
    //Print1("TwoSubSqrt3 = ", TwoSubSqrt3, 4, -1)
    //Print("")
    //Print("=======================================================================")
    Print1("      Euler = ", Euler      , 4, -1)
    //Print("")
    //Print1("      Gamma = ", Gamma      , 4, -1)
    //Print("")
    //Print1("        Phi = ", Phi        , 4, -1)
    //Print1("     PhiNeg = ", PhiNeg     , 4, -1)
    Print("")
    Print("=======================================================================")
    Print1("   OneThird = ", OneThird   , 4, -1)
    Print1("   TwoThird = ", TwoThird   , 4, -1)
ENDFUNCTION

