

FUNCTION TEST_type_vector1()
    Print("vector1.agc")
    Print("")
    Print("")
    Print("    ByteToUnit(  0) = "+str(ByteToUnit(  0)))
    Print("    ByteToUnit( 64) = "+str(ByteToUnit( 64)))
    Print("    ByteToUnit(128) = "+str(ByteToUnit(128)))
    Print("    ByteToUnit(192) = "+str(ByteToUnit(192)))
    Print("    ByteToUnit(255) = "+str(ByteToUnit(255)))
    Print("")
    Print("    UnitToByte(0.00) = "+str(UnitToByte(0.00)))
    Print("    UnitToByte(0.25) = "+str(UnitToByte(0.25)))
    Print("    UnitToByte(0.50) = "+str(UnitToByte(0.50)))
    Print("    UnitToByte(0.75) = "+str(UnitToByte(0.75)))
    Print("    UnitToByte(1.00) = "+str(UnitToByte(1.00)))
    Print("")
    Print("")
    Print("  There are no safety checks.")
    Print("")
    Print("    ByteToUnit(-64) = "+str(ByteToUnit(-64)))
    Print("    ByteToUnit(300) = "+str(ByteToUnit(300)))
    Print("")
    Print("    UnitToByte(-0.5) = "+str(UnitToByte(-0.5)))
    Print("    UnitToByte( 2.0) = "+str(UnitToByte( 2.0)))
ENDFUNCTION

